# Generated by Django 3.1.6 on 2021-03-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(max_length=100)),
                ('titlegame1', models.CharField(max_length=100)),
                ('titlegame2', models.CharField(max_length=100)),
                ('descriptiongame1', models.TextField()),
                ('descriptiongame2', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('game1url', models.CharField(max_length=100)),
                ('game2url', models.CharField(max_length=100)),
            ],
        ),
    ]
